apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-watson-mvn
  labels:
   app: spring-boot-watson-mvn
spec:
  containers:
  - name: spring-boot-watson-mvn
    image: ragudiko/spring-boot-watson-mvn
    ports:
      - containerPort: 8090
