apiVersion: v1
kind: Service
metadata:
  name: spring-boot-watson-mvn
  labels:
    app: spring-boot-watson-mvn
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8080
      nodePort: 30097
  selector:
    app: spring-boot-watson-mvn
    tier: display
